### ISSUE TITLE
Cheat engine

### ISSUE THREAD

**Issue by Ahmad148-bit** [autokey/autokey-python2#61]

**Comment by josephj11** [comment]
This branch of AutoKey is preserved for historical purposes only. It has not been actively supported for over five years.
Please use the current branch (autokey/autokey) if at all possible.

This issue has no content and will be closed if no content is added to it shortly.

----

BTW: Whenever you have a question (as opposed to an issue) it's better to post it on our [list](https://groups.google.com/forum/#!forum/autokey-users) or on [Gitter](https://gitter.im/autokey/autokey). The list is more user oriented whereas more technical questions will get a better answer on Gitter.

Both of these venues have a number of active users, so you are likely to get more, better, and faster answers on them than here on GitHub where only our very busy developers and a few users see the posts. We also prefer to have the developers developing rather than taking time to answer questions and manage issues that the user community could handle for them.

**Comment by Ahmad148-bit** [comment]
Ok
